//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tamtrutamvang.com/", ConfigurationName="ServiceReference2.WSLogin", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface WSLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/WSLogin/Login", ReplyAction="http://www.tamtrutamvang.com/WSLogin/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/WSLogin/LoginTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        int Login(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLoginChannel : WindowsFormsClient.ServiceReference2.WSLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLoginClient : System.ServiceModel.ClientBase<WindowsFormsClient.ServiceReference2.WSLogin>, WindowsFormsClient.ServiceReference2.WSLogin {
        
        public WSLoginClient() {
        }
        
        public WSLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
    }
}
