//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tamtrutamvang.com/", ConfigurationName="ServiceReference1.pis")]
    public interface pis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/GetAuthorInfo", ReplyAction="http://www.tamtrutamvang.com/pis/GetAuthorInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/GetAuthorInfoTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        string GetAuthorInfo();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/GetAuthorInfo", ReplyAction="http://www.tamtrutamvang.com/pis/GetAuthorInfoResponse")]
        System.IAsyncResult BeginGetAuthorInfo(System.AsyncCallback callback, object asyncState);
        
        string EndGetAuthorInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/FindInfoByName", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/FindInfoByNameTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] FindInfoByName(string Name, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/FindInfoByName", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByNameResponse")]
        System.IAsyncResult BeginFindInfoByName(string Name, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndFindInfoByName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/FindInfoByPhone", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByPhoneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/FindInfoByPhoneTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] FindInfoByPhone(string Phone, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/FindInfoByPhone", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByPhoneResponse")]
        System.IAsyncResult BeginFindInfoByPhone(string Phone, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndFindInfoByPhone(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/FindInfoByIdNumber", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByIdNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/FindInfoByIdNumberTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] FindInfoByIdNumber(string IdNumber, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/FindInfoByIdNumber", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByIdNumberResponse")]
        System.IAsyncResult BeginFindInfoByIdNumber(string IdNumber, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndFindInfoByIdNumber(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/FindInfoByEmail", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/FindInfoByEmailTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] FindInfoByEmail(string Email, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/FindInfoByEmail", ReplyAction="http://www.tamtrutamvang.com/pis/FindInfoByEmailResponse")]
        System.IAsyncResult BeginFindInfoByEmail(string Email, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndFindInfoByEmail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/ListPersonBySex", ReplyAction="http://www.tamtrutamvang.com/pis/ListPersonBySexResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/ListPersonBySexTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] ListPersonBySex(string Address, string Sex, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/ListPersonBySex", ReplyAction="http://www.tamtrutamvang.com/pis/ListPersonBySexResponse")]
        System.IAsyncResult BeginListPersonBySex(string Address, string Sex, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndListPersonBySex(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/ListPersonByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/ListPersonByAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/ListPersonByAddressTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] ListPersonByAddress(string Address, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/ListPersonByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/ListPersonByAddressResponse")]
        System.IAsyncResult BeginListPersonByAddress(string Address, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndListPersonByAddress(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/ListPersonByDate", ReplyAction="http://www.tamtrutamvang.com/pis/ListPersonByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/ListPersonByDateTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] ListPersonByDate(string Address, System.DateTime FromDate, System.DateTime ToDate, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/ListPersonByDate", ReplyAction="http://www.tamtrutamvang.com/pis/ListPersonByDateResponse")]
        System.IAsyncResult BeginListPersonByDate(string Address, System.DateTime FromDate, System.DateTime ToDate, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndListPersonByDate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/ListOccupationByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/ListOccupationByAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/ListOccupationByAddressTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] ListOccupationByAddress(string Address, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/ListOccupationByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/ListOccupationByAddressResponse")]
        System.IAsyncResult BeginListOccupationByAddress(string Address, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndListOccupationByAddress(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/CountSexByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/CountSexByAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/CountSexByAddressTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] CountSexByAddress(string Address, string type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/CountSexByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/CountSexByAddressResponse")]
        System.IAsyncResult BeginCountSexByAddress(string Address, string type, System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndCountSexByAddress(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/LoadData", ReplyAction="http://www.tamtrutamvang.com/pis/LoadDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/LoadDataTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        TTTVService.TranferRecord[] LoadData();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/LoadData", ReplyAction="http://www.tamtrutamvang.com/pis/LoadDataResponse")]
        System.IAsyncResult BeginLoadData(System.AsyncCallback callback, object asyncState);
        
        TTTVService.TranferRecord[] EndLoadData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/Login", ReplyAction="http://www.tamtrutamvang.com/pis/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TTTVService.TrackedFault), Action="http://www.tamtrutamvang.com/pis/LoginTrackedFaultFault", Name="TrackedFault", Namespace="http://schemas.datacontract.org/2004/07/TTTVService")]
        int Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/Login", ReplyAction="http://www.tamtrutamvang.com/pis/LoginResponse")]
        System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState);
        
        int EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.tamtrutamvang.com/pis/ImportDataFromFile")]
        void ImportDataFromFile(string[] file);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/ImportDataFromFile")]
        System.IAsyncResult BeginImportDataFromFile(string[] file, System.AsyncCallback callback, object asyncState);
        
        void EndImportDataFromFile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.tamtrutamvang.com/pis/InsertInfomation")]
        void InsertInfomation(TTTVService.TranferRecord data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/InsertInfomation")]
        System.IAsyncResult BeginInsertInfomation(TTTVService.TranferRecord data, System.AsyncCallback callback, object asyncState);
        
        void EndInsertInfomation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.tamtrutamvang.com/pis/UpdatInformation")]
        void UpdatInformation(int Id, TTTVService.TranferRecord data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/UpdatInformation")]
        System.IAsyncResult BeginUpdatInformation(int Id, TTTVService.TranferRecord data, System.AsyncCallback callback, object asyncState);
        
        void EndUpdatInformation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.tamtrutamvang.com/pis/DeleteInformation")]
        void DeleteInformation(int Id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/DeleteInformation")]
        System.IAsyncResult BeginDeleteInformation(int Id, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteInformation(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pisChannel : WindowsFormsClient.ServiceReference1.pis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAuthorInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAuthorInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindInfoByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindInfoByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindInfoByPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindInfoByPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindInfoByIdNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindInfoByIdNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindInfoByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindInfoByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListPersonBySexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListPersonBySexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListPersonByAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListPersonByAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListPersonByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListPersonByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListOccupationByAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListOccupationByAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountSexByAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CountSexByAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TTTVService.TranferRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TTTVService.TranferRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pisClient : System.ServiceModel.ClientBase<WindowsFormsClient.ServiceReference1.pis>, WindowsFormsClient.ServiceReference1.pis {
        
        private BeginOperationDelegate onBeginGetAuthorInfoDelegate;
        
        private EndOperationDelegate onEndGetAuthorInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAuthorInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindInfoByNameDelegate;
        
        private EndOperationDelegate onEndFindInfoByNameDelegate;
        
        private System.Threading.SendOrPostCallback onFindInfoByNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindInfoByPhoneDelegate;
        
        private EndOperationDelegate onEndFindInfoByPhoneDelegate;
        
        private System.Threading.SendOrPostCallback onFindInfoByPhoneCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindInfoByIdNumberDelegate;
        
        private EndOperationDelegate onEndFindInfoByIdNumberDelegate;
        
        private System.Threading.SendOrPostCallback onFindInfoByIdNumberCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindInfoByEmailDelegate;
        
        private EndOperationDelegate onEndFindInfoByEmailDelegate;
        
        private System.Threading.SendOrPostCallback onFindInfoByEmailCompletedDelegate;
        
        private BeginOperationDelegate onBeginListPersonBySexDelegate;
        
        private EndOperationDelegate onEndListPersonBySexDelegate;
        
        private System.Threading.SendOrPostCallback onListPersonBySexCompletedDelegate;
        
        private BeginOperationDelegate onBeginListPersonByAddressDelegate;
        
        private EndOperationDelegate onEndListPersonByAddressDelegate;
        
        private System.Threading.SendOrPostCallback onListPersonByAddressCompletedDelegate;
        
        private BeginOperationDelegate onBeginListPersonByDateDelegate;
        
        private EndOperationDelegate onEndListPersonByDateDelegate;
        
        private System.Threading.SendOrPostCallback onListPersonByDateCompletedDelegate;
        
        private BeginOperationDelegate onBeginListOccupationByAddressDelegate;
        
        private EndOperationDelegate onEndListOccupationByAddressDelegate;
        
        private System.Threading.SendOrPostCallback onListOccupationByAddressCompletedDelegate;
        
        private BeginOperationDelegate onBeginCountSexByAddressDelegate;
        
        private EndOperationDelegate onEndCountSexByAddressDelegate;
        
        private System.Threading.SendOrPostCallback onCountSexByAddressCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoadDataDelegate;
        
        private EndOperationDelegate onEndLoadDataDelegate;
        
        private System.Threading.SendOrPostCallback onLoadDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginImportDataFromFileDelegate;
        
        private EndOperationDelegate onEndImportDataFromFileDelegate;
        
        private System.Threading.SendOrPostCallback onImportDataFromFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertInfomationDelegate;
        
        private EndOperationDelegate onEndInsertInfomationDelegate;
        
        private System.Threading.SendOrPostCallback onInsertInfomationCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatInformationDelegate;
        
        private EndOperationDelegate onEndUpdatInformationDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteInformationDelegate;
        
        private EndOperationDelegate onEndDeleteInformationDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteInformationCompletedDelegate;
        
        public pisClient() {
        }
        
        public pisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public pisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAuthorInfoCompletedEventArgs> GetAuthorInfoCompleted;
        
        public event System.EventHandler<FindInfoByNameCompletedEventArgs> FindInfoByNameCompleted;
        
        public event System.EventHandler<FindInfoByPhoneCompletedEventArgs> FindInfoByPhoneCompleted;
        
        public event System.EventHandler<FindInfoByIdNumberCompletedEventArgs> FindInfoByIdNumberCompleted;
        
        public event System.EventHandler<FindInfoByEmailCompletedEventArgs> FindInfoByEmailCompleted;
        
        public event System.EventHandler<ListPersonBySexCompletedEventArgs> ListPersonBySexCompleted;
        
        public event System.EventHandler<ListPersonByAddressCompletedEventArgs> ListPersonByAddressCompleted;
        
        public event System.EventHandler<ListPersonByDateCompletedEventArgs> ListPersonByDateCompleted;
        
        public event System.EventHandler<ListOccupationByAddressCompletedEventArgs> ListOccupationByAddressCompleted;
        
        public event System.EventHandler<CountSexByAddressCompletedEventArgs> CountSexByAddressCompleted;
        
        public event System.EventHandler<LoadDataCompletedEventArgs> LoadDataCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ImportDataFromFileCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InsertInfomationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdatInformationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteInformationCompleted;
        
        public string GetAuthorInfo() {
            return base.Channel.GetAuthorInfo();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAuthorInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAuthorInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetAuthorInfo(System.IAsyncResult result) {
            return base.Channel.EndGetAuthorInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetAuthorInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAuthorInfo(callback, asyncState);
        }
        
        private object[] OnEndGetAuthorInfo(System.IAsyncResult result) {
            string retVal = this.EndGetAuthorInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAuthorInfoCompleted(object state) {
            if ((this.GetAuthorInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAuthorInfoCompleted(this, new GetAuthorInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAuthorInfoAsync() {
            this.GetAuthorInfoAsync(null);
        }
        
        public void GetAuthorInfoAsync(object userState) {
            if ((this.onBeginGetAuthorInfoDelegate == null)) {
                this.onBeginGetAuthorInfoDelegate = new BeginOperationDelegate(this.OnBeginGetAuthorInfo);
            }
            if ((this.onEndGetAuthorInfoDelegate == null)) {
                this.onEndGetAuthorInfoDelegate = new EndOperationDelegate(this.OnEndGetAuthorInfo);
            }
            if ((this.onGetAuthorInfoCompletedDelegate == null)) {
                this.onGetAuthorInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthorInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAuthorInfoDelegate, null, this.onEndGetAuthorInfoDelegate, this.onGetAuthorInfoCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] FindInfoByName(string Name, string type) {
            return base.Channel.FindInfoByName(Name, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFindInfoByName(string Name, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindInfoByName(Name, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndFindInfoByName(System.IAsyncResult result) {
            return base.Channel.EndFindInfoByName(result);
        }
        
        private System.IAsyncResult OnBeginFindInfoByName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Name = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            return this.BeginFindInfoByName(Name, type, callback, asyncState);
        }
        
        private object[] OnEndFindInfoByName(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndFindInfoByName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindInfoByNameCompleted(object state) {
            if ((this.FindInfoByNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindInfoByNameCompleted(this, new FindInfoByNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindInfoByNameAsync(string Name, string type) {
            this.FindInfoByNameAsync(Name, type, null);
        }
        
        public void FindInfoByNameAsync(string Name, string type, object userState) {
            if ((this.onBeginFindInfoByNameDelegate == null)) {
                this.onBeginFindInfoByNameDelegate = new BeginOperationDelegate(this.OnBeginFindInfoByName);
            }
            if ((this.onEndFindInfoByNameDelegate == null)) {
                this.onEndFindInfoByNameDelegate = new EndOperationDelegate(this.OnEndFindInfoByName);
            }
            if ((this.onFindInfoByNameCompletedDelegate == null)) {
                this.onFindInfoByNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindInfoByNameCompleted);
            }
            base.InvokeAsync(this.onBeginFindInfoByNameDelegate, new object[] {
                        Name,
                        type}, this.onEndFindInfoByNameDelegate, this.onFindInfoByNameCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] FindInfoByPhone(string Phone, string type) {
            return base.Channel.FindInfoByPhone(Phone, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFindInfoByPhone(string Phone, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindInfoByPhone(Phone, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndFindInfoByPhone(System.IAsyncResult result) {
            return base.Channel.EndFindInfoByPhone(result);
        }
        
        private System.IAsyncResult OnBeginFindInfoByPhone(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Phone = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            return this.BeginFindInfoByPhone(Phone, type, callback, asyncState);
        }
        
        private object[] OnEndFindInfoByPhone(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndFindInfoByPhone(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindInfoByPhoneCompleted(object state) {
            if ((this.FindInfoByPhoneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindInfoByPhoneCompleted(this, new FindInfoByPhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindInfoByPhoneAsync(string Phone, string type) {
            this.FindInfoByPhoneAsync(Phone, type, null);
        }
        
        public void FindInfoByPhoneAsync(string Phone, string type, object userState) {
            if ((this.onBeginFindInfoByPhoneDelegate == null)) {
                this.onBeginFindInfoByPhoneDelegate = new BeginOperationDelegate(this.OnBeginFindInfoByPhone);
            }
            if ((this.onEndFindInfoByPhoneDelegate == null)) {
                this.onEndFindInfoByPhoneDelegate = new EndOperationDelegate(this.OnEndFindInfoByPhone);
            }
            if ((this.onFindInfoByPhoneCompletedDelegate == null)) {
                this.onFindInfoByPhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindInfoByPhoneCompleted);
            }
            base.InvokeAsync(this.onBeginFindInfoByPhoneDelegate, new object[] {
                        Phone,
                        type}, this.onEndFindInfoByPhoneDelegate, this.onFindInfoByPhoneCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] FindInfoByIdNumber(string IdNumber, string type) {
            return base.Channel.FindInfoByIdNumber(IdNumber, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFindInfoByIdNumber(string IdNumber, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindInfoByIdNumber(IdNumber, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndFindInfoByIdNumber(System.IAsyncResult result) {
            return base.Channel.EndFindInfoByIdNumber(result);
        }
        
        private System.IAsyncResult OnBeginFindInfoByIdNumber(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string IdNumber = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            return this.BeginFindInfoByIdNumber(IdNumber, type, callback, asyncState);
        }
        
        private object[] OnEndFindInfoByIdNumber(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndFindInfoByIdNumber(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindInfoByIdNumberCompleted(object state) {
            if ((this.FindInfoByIdNumberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindInfoByIdNumberCompleted(this, new FindInfoByIdNumberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindInfoByIdNumberAsync(string IdNumber, string type) {
            this.FindInfoByIdNumberAsync(IdNumber, type, null);
        }
        
        public void FindInfoByIdNumberAsync(string IdNumber, string type, object userState) {
            if ((this.onBeginFindInfoByIdNumberDelegate == null)) {
                this.onBeginFindInfoByIdNumberDelegate = new BeginOperationDelegate(this.OnBeginFindInfoByIdNumber);
            }
            if ((this.onEndFindInfoByIdNumberDelegate == null)) {
                this.onEndFindInfoByIdNumberDelegate = new EndOperationDelegate(this.OnEndFindInfoByIdNumber);
            }
            if ((this.onFindInfoByIdNumberCompletedDelegate == null)) {
                this.onFindInfoByIdNumberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindInfoByIdNumberCompleted);
            }
            base.InvokeAsync(this.onBeginFindInfoByIdNumberDelegate, new object[] {
                        IdNumber,
                        type}, this.onEndFindInfoByIdNumberDelegate, this.onFindInfoByIdNumberCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] FindInfoByEmail(string Email, string type) {
            return base.Channel.FindInfoByEmail(Email, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFindInfoByEmail(string Email, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindInfoByEmail(Email, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndFindInfoByEmail(System.IAsyncResult result) {
            return base.Channel.EndFindInfoByEmail(result);
        }
        
        private System.IAsyncResult OnBeginFindInfoByEmail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Email = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            return this.BeginFindInfoByEmail(Email, type, callback, asyncState);
        }
        
        private object[] OnEndFindInfoByEmail(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndFindInfoByEmail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindInfoByEmailCompleted(object state) {
            if ((this.FindInfoByEmailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindInfoByEmailCompleted(this, new FindInfoByEmailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindInfoByEmailAsync(string Email, string type) {
            this.FindInfoByEmailAsync(Email, type, null);
        }
        
        public void FindInfoByEmailAsync(string Email, string type, object userState) {
            if ((this.onBeginFindInfoByEmailDelegate == null)) {
                this.onBeginFindInfoByEmailDelegate = new BeginOperationDelegate(this.OnBeginFindInfoByEmail);
            }
            if ((this.onEndFindInfoByEmailDelegate == null)) {
                this.onEndFindInfoByEmailDelegate = new EndOperationDelegate(this.OnEndFindInfoByEmail);
            }
            if ((this.onFindInfoByEmailCompletedDelegate == null)) {
                this.onFindInfoByEmailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindInfoByEmailCompleted);
            }
            base.InvokeAsync(this.onBeginFindInfoByEmailDelegate, new object[] {
                        Email,
                        type}, this.onEndFindInfoByEmailDelegate, this.onFindInfoByEmailCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] ListPersonBySex(string Address, string Sex, string type) {
            return base.Channel.ListPersonBySex(Address, Sex, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListPersonBySex(string Address, string Sex, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListPersonBySex(Address, Sex, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndListPersonBySex(System.IAsyncResult result) {
            return base.Channel.EndListPersonBySex(result);
        }
        
        private System.IAsyncResult OnBeginListPersonBySex(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Address = ((string)(inValues[0]));
            string Sex = ((string)(inValues[1]));
            string type = ((string)(inValues[2]));
            return this.BeginListPersonBySex(Address, Sex, type, callback, asyncState);
        }
        
        private object[] OnEndListPersonBySex(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndListPersonBySex(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListPersonBySexCompleted(object state) {
            if ((this.ListPersonBySexCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListPersonBySexCompleted(this, new ListPersonBySexCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListPersonBySexAsync(string Address, string Sex, string type) {
            this.ListPersonBySexAsync(Address, Sex, type, null);
        }
        
        public void ListPersonBySexAsync(string Address, string Sex, string type, object userState) {
            if ((this.onBeginListPersonBySexDelegate == null)) {
                this.onBeginListPersonBySexDelegate = new BeginOperationDelegate(this.OnBeginListPersonBySex);
            }
            if ((this.onEndListPersonBySexDelegate == null)) {
                this.onEndListPersonBySexDelegate = new EndOperationDelegate(this.OnEndListPersonBySex);
            }
            if ((this.onListPersonBySexCompletedDelegate == null)) {
                this.onListPersonBySexCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListPersonBySexCompleted);
            }
            base.InvokeAsync(this.onBeginListPersonBySexDelegate, new object[] {
                        Address,
                        Sex,
                        type}, this.onEndListPersonBySexDelegate, this.onListPersonBySexCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] ListPersonByAddress(string Address, string type) {
            return base.Channel.ListPersonByAddress(Address, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListPersonByAddress(string Address, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListPersonByAddress(Address, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndListPersonByAddress(System.IAsyncResult result) {
            return base.Channel.EndListPersonByAddress(result);
        }
        
        private System.IAsyncResult OnBeginListPersonByAddress(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Address = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            return this.BeginListPersonByAddress(Address, type, callback, asyncState);
        }
        
        private object[] OnEndListPersonByAddress(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndListPersonByAddress(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListPersonByAddressCompleted(object state) {
            if ((this.ListPersonByAddressCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListPersonByAddressCompleted(this, new ListPersonByAddressCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListPersonByAddressAsync(string Address, string type) {
            this.ListPersonByAddressAsync(Address, type, null);
        }
        
        public void ListPersonByAddressAsync(string Address, string type, object userState) {
            if ((this.onBeginListPersonByAddressDelegate == null)) {
                this.onBeginListPersonByAddressDelegate = new BeginOperationDelegate(this.OnBeginListPersonByAddress);
            }
            if ((this.onEndListPersonByAddressDelegate == null)) {
                this.onEndListPersonByAddressDelegate = new EndOperationDelegate(this.OnEndListPersonByAddress);
            }
            if ((this.onListPersonByAddressCompletedDelegate == null)) {
                this.onListPersonByAddressCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListPersonByAddressCompleted);
            }
            base.InvokeAsync(this.onBeginListPersonByAddressDelegate, new object[] {
                        Address,
                        type}, this.onEndListPersonByAddressDelegate, this.onListPersonByAddressCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] ListPersonByDate(string Address, System.DateTime FromDate, System.DateTime ToDate, string type) {
            return base.Channel.ListPersonByDate(Address, FromDate, ToDate, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListPersonByDate(string Address, System.DateTime FromDate, System.DateTime ToDate, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListPersonByDate(Address, FromDate, ToDate, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndListPersonByDate(System.IAsyncResult result) {
            return base.Channel.EndListPersonByDate(result);
        }
        
        private System.IAsyncResult OnBeginListPersonByDate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Address = ((string)(inValues[0]));
            System.DateTime FromDate = ((System.DateTime)(inValues[1]));
            System.DateTime ToDate = ((System.DateTime)(inValues[2]));
            string type = ((string)(inValues[3]));
            return this.BeginListPersonByDate(Address, FromDate, ToDate, type, callback, asyncState);
        }
        
        private object[] OnEndListPersonByDate(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndListPersonByDate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListPersonByDateCompleted(object state) {
            if ((this.ListPersonByDateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListPersonByDateCompleted(this, new ListPersonByDateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListPersonByDateAsync(string Address, System.DateTime FromDate, System.DateTime ToDate, string type) {
            this.ListPersonByDateAsync(Address, FromDate, ToDate, type, null);
        }
        
        public void ListPersonByDateAsync(string Address, System.DateTime FromDate, System.DateTime ToDate, string type, object userState) {
            if ((this.onBeginListPersonByDateDelegate == null)) {
                this.onBeginListPersonByDateDelegate = new BeginOperationDelegate(this.OnBeginListPersonByDate);
            }
            if ((this.onEndListPersonByDateDelegate == null)) {
                this.onEndListPersonByDateDelegate = new EndOperationDelegate(this.OnEndListPersonByDate);
            }
            if ((this.onListPersonByDateCompletedDelegate == null)) {
                this.onListPersonByDateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListPersonByDateCompleted);
            }
            base.InvokeAsync(this.onBeginListPersonByDateDelegate, new object[] {
                        Address,
                        FromDate,
                        ToDate,
                        type}, this.onEndListPersonByDateDelegate, this.onListPersonByDateCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] ListOccupationByAddress(string Address, string type) {
            return base.Channel.ListOccupationByAddress(Address, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListOccupationByAddress(string Address, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListOccupationByAddress(Address, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndListOccupationByAddress(System.IAsyncResult result) {
            return base.Channel.EndListOccupationByAddress(result);
        }
        
        private System.IAsyncResult OnBeginListOccupationByAddress(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Address = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            return this.BeginListOccupationByAddress(Address, type, callback, asyncState);
        }
        
        private object[] OnEndListOccupationByAddress(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndListOccupationByAddress(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListOccupationByAddressCompleted(object state) {
            if ((this.ListOccupationByAddressCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListOccupationByAddressCompleted(this, new ListOccupationByAddressCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListOccupationByAddressAsync(string Address, string type) {
            this.ListOccupationByAddressAsync(Address, type, null);
        }
        
        public void ListOccupationByAddressAsync(string Address, string type, object userState) {
            if ((this.onBeginListOccupationByAddressDelegate == null)) {
                this.onBeginListOccupationByAddressDelegate = new BeginOperationDelegate(this.OnBeginListOccupationByAddress);
            }
            if ((this.onEndListOccupationByAddressDelegate == null)) {
                this.onEndListOccupationByAddressDelegate = new EndOperationDelegate(this.OnEndListOccupationByAddress);
            }
            if ((this.onListOccupationByAddressCompletedDelegate == null)) {
                this.onListOccupationByAddressCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListOccupationByAddressCompleted);
            }
            base.InvokeAsync(this.onBeginListOccupationByAddressDelegate, new object[] {
                        Address,
                        type}, this.onEndListOccupationByAddressDelegate, this.onListOccupationByAddressCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] CountSexByAddress(string Address, string type) {
            return base.Channel.CountSexByAddress(Address, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCountSexByAddress(string Address, string type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCountSexByAddress(Address, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndCountSexByAddress(System.IAsyncResult result) {
            return base.Channel.EndCountSexByAddress(result);
        }
        
        private System.IAsyncResult OnBeginCountSexByAddress(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Address = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            return this.BeginCountSexByAddress(Address, type, callback, asyncState);
        }
        
        private object[] OnEndCountSexByAddress(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndCountSexByAddress(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCountSexByAddressCompleted(object state) {
            if ((this.CountSexByAddressCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CountSexByAddressCompleted(this, new CountSexByAddressCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CountSexByAddressAsync(string Address, string type) {
            this.CountSexByAddressAsync(Address, type, null);
        }
        
        public void CountSexByAddressAsync(string Address, string type, object userState) {
            if ((this.onBeginCountSexByAddressDelegate == null)) {
                this.onBeginCountSexByAddressDelegate = new BeginOperationDelegate(this.OnBeginCountSexByAddress);
            }
            if ((this.onEndCountSexByAddressDelegate == null)) {
                this.onEndCountSexByAddressDelegate = new EndOperationDelegate(this.OnEndCountSexByAddress);
            }
            if ((this.onCountSexByAddressCompletedDelegate == null)) {
                this.onCountSexByAddressCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCountSexByAddressCompleted);
            }
            base.InvokeAsync(this.onBeginCountSexByAddressDelegate, new object[] {
                        Address,
                        type}, this.onEndCountSexByAddressDelegate, this.onCountSexByAddressCompletedDelegate, userState);
        }
        
        public TTTVService.TranferRecord[] LoadData() {
            return base.Channel.LoadData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLoadData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoadData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TTTVService.TranferRecord[] EndLoadData(System.IAsyncResult result) {
            return base.Channel.EndLoadData(result);
        }
        
        private System.IAsyncResult OnBeginLoadData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginLoadData(callback, asyncState);
        }
        
        private object[] OnEndLoadData(System.IAsyncResult result) {
            TTTVService.TranferRecord[] retVal = this.EndLoadData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoadDataCompleted(object state) {
            if ((this.LoadDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoadDataCompleted(this, new LoadDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoadDataAsync() {
            this.LoadDataAsync(null);
        }
        
        public void LoadDataAsync(object userState) {
            if ((this.onBeginLoadDataDelegate == null)) {
                this.onBeginLoadDataDelegate = new BeginOperationDelegate(this.OnBeginLoadData);
            }
            if ((this.onEndLoadDataDelegate == null)) {
                this.onEndLoadDataDelegate = new EndOperationDelegate(this.OnEndLoadData);
            }
            if ((this.onLoadDataCompletedDelegate == null)) {
                this.onLoadDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoadDataCompleted);
            }
            base.InvokeAsync(this.onBeginLoadDataDelegate, null, this.onEndLoadDataDelegate, this.onLoadDataCompletedDelegate, userState);
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginLogin(username, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            int retVal = this.EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        public void LoginAsync(string username, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        username,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        public void ImportDataFromFile(string[] file) {
            base.Channel.ImportDataFromFile(file);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginImportDataFromFile(string[] file, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginImportDataFromFile(file, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndImportDataFromFile(System.IAsyncResult result) {
            base.Channel.EndImportDataFromFile(result);
        }
        
        private System.IAsyncResult OnBeginImportDataFromFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string[] file = ((string[])(inValues[0]));
            return this.BeginImportDataFromFile(file, callback, asyncState);
        }
        
        private object[] OnEndImportDataFromFile(System.IAsyncResult result) {
            this.EndImportDataFromFile(result);
            return null;
        }
        
        private void OnImportDataFromFileCompleted(object state) {
            if ((this.ImportDataFromFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ImportDataFromFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ImportDataFromFileAsync(string[] file) {
            this.ImportDataFromFileAsync(file, null);
        }
        
        public void ImportDataFromFileAsync(string[] file, object userState) {
            if ((this.onBeginImportDataFromFileDelegate == null)) {
                this.onBeginImportDataFromFileDelegate = new BeginOperationDelegate(this.OnBeginImportDataFromFile);
            }
            if ((this.onEndImportDataFromFileDelegate == null)) {
                this.onEndImportDataFromFileDelegate = new EndOperationDelegate(this.OnEndImportDataFromFile);
            }
            if ((this.onImportDataFromFileCompletedDelegate == null)) {
                this.onImportDataFromFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnImportDataFromFileCompleted);
            }
            base.InvokeAsync(this.onBeginImportDataFromFileDelegate, new object[] {
                        file}, this.onEndImportDataFromFileDelegate, this.onImportDataFromFileCompletedDelegate, userState);
        }
        
        public void InsertInfomation(TTTVService.TranferRecord data) {
            base.Channel.InsertInfomation(data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInsertInfomation(TTTVService.TranferRecord data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertInfomation(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndInsertInfomation(System.IAsyncResult result) {
            base.Channel.EndInsertInfomation(result);
        }
        
        private System.IAsyncResult OnBeginInsertInfomation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TTTVService.TranferRecord data = ((TTTVService.TranferRecord)(inValues[0]));
            return this.BeginInsertInfomation(data, callback, asyncState);
        }
        
        private object[] OnEndInsertInfomation(System.IAsyncResult result) {
            this.EndInsertInfomation(result);
            return null;
        }
        
        private void OnInsertInfomationCompleted(object state) {
            if ((this.InsertInfomationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertInfomationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertInfomationAsync(TTTVService.TranferRecord data) {
            this.InsertInfomationAsync(data, null);
        }
        
        public void InsertInfomationAsync(TTTVService.TranferRecord data, object userState) {
            if ((this.onBeginInsertInfomationDelegate == null)) {
                this.onBeginInsertInfomationDelegate = new BeginOperationDelegate(this.OnBeginInsertInfomation);
            }
            if ((this.onEndInsertInfomationDelegate == null)) {
                this.onEndInsertInfomationDelegate = new EndOperationDelegate(this.OnEndInsertInfomation);
            }
            if ((this.onInsertInfomationCompletedDelegate == null)) {
                this.onInsertInfomationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertInfomationCompleted);
            }
            base.InvokeAsync(this.onBeginInsertInfomationDelegate, new object[] {
                        data}, this.onEndInsertInfomationDelegate, this.onInsertInfomationCompletedDelegate, userState);
        }
        
        public void UpdatInformation(int Id, TTTVService.TranferRecord data) {
            base.Channel.UpdatInformation(Id, data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdatInformation(int Id, TTTVService.TranferRecord data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatInformation(Id, data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndUpdatInformation(System.IAsyncResult result) {
            base.Channel.EndUpdatInformation(result);
        }
        
        private System.IAsyncResult OnBeginUpdatInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Id = ((int)(inValues[0]));
            TTTVService.TranferRecord data = ((TTTVService.TranferRecord)(inValues[1]));
            return this.BeginUpdatInformation(Id, data, callback, asyncState);
        }
        
        private object[] OnEndUpdatInformation(System.IAsyncResult result) {
            this.EndUpdatInformation(result);
            return null;
        }
        
        private void OnUpdatInformationCompleted(object state) {
            if ((this.UpdatInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatInformationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatInformationAsync(int Id, TTTVService.TranferRecord data) {
            this.UpdatInformationAsync(Id, data, null);
        }
        
        public void UpdatInformationAsync(int Id, TTTVService.TranferRecord data, object userState) {
            if ((this.onBeginUpdatInformationDelegate == null)) {
                this.onBeginUpdatInformationDelegate = new BeginOperationDelegate(this.OnBeginUpdatInformation);
            }
            if ((this.onEndUpdatInformationDelegate == null)) {
                this.onEndUpdatInformationDelegate = new EndOperationDelegate(this.OnEndUpdatInformation);
            }
            if ((this.onUpdatInformationCompletedDelegate == null)) {
                this.onUpdatInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatInformationCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatInformationDelegate, new object[] {
                        Id,
                        data}, this.onEndUpdatInformationDelegate, this.onUpdatInformationCompletedDelegate, userState);
        }
        
        public void DeleteInformation(int Id) {
            base.Channel.DeleteInformation(Id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteInformation(int Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteInformation(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteInformation(System.IAsyncResult result) {
            base.Channel.EndDeleteInformation(result);
        }
        
        private System.IAsyncResult OnBeginDeleteInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Id = ((int)(inValues[0]));
            return this.BeginDeleteInformation(Id, callback, asyncState);
        }
        
        private object[] OnEndDeleteInformation(System.IAsyncResult result) {
            this.EndDeleteInformation(result);
            return null;
        }
        
        private void OnDeleteInformationCompleted(object state) {
            if ((this.DeleteInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteInformationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteInformationAsync(int Id) {
            this.DeleteInformationAsync(Id, null);
        }
        
        public void DeleteInformationAsync(int Id, object userState) {
            if ((this.onBeginDeleteInformationDelegate == null)) {
                this.onBeginDeleteInformationDelegate = new BeginOperationDelegate(this.OnBeginDeleteInformation);
            }
            if ((this.onEndDeleteInformationDelegate == null)) {
                this.onEndDeleteInformationDelegate = new EndOperationDelegate(this.OnEndDeleteInformation);
            }
            if ((this.onDeleteInformationCompletedDelegate == null)) {
                this.onDeleteInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteInformationCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteInformationDelegate, new object[] {
                        Id}, this.onEndDeleteInformationDelegate, this.onDeleteInformationCompletedDelegate, userState);
        }
    }
}
