//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tamtrutamvang.com/", ConfigurationName="ServiceReference1.pis")]
    public interface pis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/AuthorInformation", ReplyAction="http://www.tamtrutamvang.com/pis/AuthorInformationResponse")]
        string AuthorInformation();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/AuthorInformation", ReplyAction="http://www.tamtrutamvang.com/pis/AuthorInformationResponse")]
        System.IAsyncResult BeginAuthorInformation(System.AsyncCallback callback, object asyncState);
        
        string EndAuthorInformation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/GetInfoByName", ReplyAction="http://www.tamtrutamvang.com/pis/GetInfoByNameResponse")]
        string GetInfoByName(string Name);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/GetInfoByName", ReplyAction="http://www.tamtrutamvang.com/pis/GetInfoByNameResponse")]
        System.IAsyncResult BeginGetInfoByName(string Name, System.AsyncCallback callback, object asyncState);
        
        string EndGetInfoByName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tamtrutamvang.com/pis/GetInfoByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/GetInfoByAddressResponse")]
        string GetInfoByAddress(string Adress);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.tamtrutamvang.com/pis/GetInfoByAddress", ReplyAction="http://www.tamtrutamvang.com/pis/GetInfoByAddressResponse")]
        System.IAsyncResult BeginGetInfoByAddress(string Adress, System.AsyncCallback callback, object asyncState);
        
        string EndGetInfoByAddress(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pisChannel : WindowsFormsClient.ServiceReference1.pis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthorInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInfoByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInfoByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInfoByAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInfoByAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pisClient : System.ServiceModel.ClientBase<WindowsFormsClient.ServiceReference1.pis>, WindowsFormsClient.ServiceReference1.pis {
        
        private BeginOperationDelegate onBeginAuthorInformationDelegate;
        
        private EndOperationDelegate onEndAuthorInformationDelegate;
        
        private System.Threading.SendOrPostCallback onAuthorInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetInfoByNameDelegate;
        
        private EndOperationDelegate onEndGetInfoByNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetInfoByNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetInfoByAddressDelegate;
        
        private EndOperationDelegate onEndGetInfoByAddressDelegate;
        
        private System.Threading.SendOrPostCallback onGetInfoByAddressCompletedDelegate;
        
        public pisClient() {
        }
        
        public pisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public pisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AuthorInformationCompletedEventArgs> AuthorInformationCompleted;
        
        public event System.EventHandler<GetInfoByNameCompletedEventArgs> GetInfoByNameCompleted;
        
        public event System.EventHandler<GetInfoByAddressCompletedEventArgs> GetInfoByAddressCompleted;
        
        public string AuthorInformation() {
            return base.Channel.AuthorInformation();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAuthorInformation(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthorInformation(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndAuthorInformation(System.IAsyncResult result) {
            return base.Channel.EndAuthorInformation(result);
        }
        
        private System.IAsyncResult OnBeginAuthorInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginAuthorInformation(callback, asyncState);
        }
        
        private object[] OnEndAuthorInformation(System.IAsyncResult result) {
            string retVal = this.EndAuthorInformation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthorInformationCompleted(object state) {
            if ((this.AuthorInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthorInformationCompleted(this, new AuthorInformationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthorInformationAsync() {
            this.AuthorInformationAsync(null);
        }
        
        public void AuthorInformationAsync(object userState) {
            if ((this.onBeginAuthorInformationDelegate == null)) {
                this.onBeginAuthorInformationDelegate = new BeginOperationDelegate(this.OnBeginAuthorInformation);
            }
            if ((this.onEndAuthorInformationDelegate == null)) {
                this.onEndAuthorInformationDelegate = new EndOperationDelegate(this.OnEndAuthorInformation);
            }
            if ((this.onAuthorInformationCompletedDelegate == null)) {
                this.onAuthorInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthorInformationCompleted);
            }
            base.InvokeAsync(this.onBeginAuthorInformationDelegate, null, this.onEndAuthorInformationDelegate, this.onAuthorInformationCompletedDelegate, userState);
        }
        
        public string GetInfoByName(string Name) {
            return base.Channel.GetInfoByName(Name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetInfoByName(string Name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInfoByName(Name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetInfoByName(System.IAsyncResult result) {
            return base.Channel.EndGetInfoByName(result);
        }
        
        private System.IAsyncResult OnBeginGetInfoByName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Name = ((string)(inValues[0]));
            return this.BeginGetInfoByName(Name, callback, asyncState);
        }
        
        private object[] OnEndGetInfoByName(System.IAsyncResult result) {
            string retVal = this.EndGetInfoByName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInfoByNameCompleted(object state) {
            if ((this.GetInfoByNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInfoByNameCompleted(this, new GetInfoByNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInfoByNameAsync(string Name) {
            this.GetInfoByNameAsync(Name, null);
        }
        
        public void GetInfoByNameAsync(string Name, object userState) {
            if ((this.onBeginGetInfoByNameDelegate == null)) {
                this.onBeginGetInfoByNameDelegate = new BeginOperationDelegate(this.OnBeginGetInfoByName);
            }
            if ((this.onEndGetInfoByNameDelegate == null)) {
                this.onEndGetInfoByNameDelegate = new EndOperationDelegate(this.OnEndGetInfoByName);
            }
            if ((this.onGetInfoByNameCompletedDelegate == null)) {
                this.onGetInfoByNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInfoByNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetInfoByNameDelegate, new object[] {
                        Name}, this.onEndGetInfoByNameDelegate, this.onGetInfoByNameCompletedDelegate, userState);
        }
        
        public string GetInfoByAddress(string Adress) {
            return base.Channel.GetInfoByAddress(Adress);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetInfoByAddress(string Adress, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInfoByAddress(Adress, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetInfoByAddress(System.IAsyncResult result) {
            return base.Channel.EndGetInfoByAddress(result);
        }
        
        private System.IAsyncResult OnBeginGetInfoByAddress(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Adress = ((string)(inValues[0]));
            return this.BeginGetInfoByAddress(Adress, callback, asyncState);
        }
        
        private object[] OnEndGetInfoByAddress(System.IAsyncResult result) {
            string retVal = this.EndGetInfoByAddress(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInfoByAddressCompleted(object state) {
            if ((this.GetInfoByAddressCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInfoByAddressCompleted(this, new GetInfoByAddressCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInfoByAddressAsync(string Adress) {
            this.GetInfoByAddressAsync(Adress, null);
        }
        
        public void GetInfoByAddressAsync(string Adress, object userState) {
            if ((this.onBeginGetInfoByAddressDelegate == null)) {
                this.onBeginGetInfoByAddressDelegate = new BeginOperationDelegate(this.OnBeginGetInfoByAddress);
            }
            if ((this.onEndGetInfoByAddressDelegate == null)) {
                this.onEndGetInfoByAddressDelegate = new EndOperationDelegate(this.OnEndGetInfoByAddress);
            }
            if ((this.onGetInfoByAddressCompletedDelegate == null)) {
                this.onGetInfoByAddressCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInfoByAddressCompleted);
            }
            base.InvokeAsync(this.onBeginGetInfoByAddressDelegate, new object[] {
                        Adress}, this.onEndGetInfoByAddressDelegate, this.onGetInfoByAddressCompletedDelegate, userState);
        }
    }
}
